package dev.waylon.player.apis.features.home.recommend

import dev.waylon.player.apis.common.ApiService
import dev.waylon.player.apis.common.client.ApiClient
import dev.waylon.player.apis.common.constants.UrlConstants
import dev.waylon.player.apis.common.extensions.wbiGet
import io.ktor.client.statement.HttpResponse

/**
 * Home Recommendation API Service
 * 
 * Provides home page recommendation API: [UrlConstants.ENDPOINT_HOME_RECOMMENDATION]
 */
object HomeRecommendationService : ApiService<HomeRecommendRequest> {

    override suspend fun execute(request: HomeRecommendRequest): HttpResponse {
        // Build parameters map
        val params = mutableMapOf<String, Any?>(
            "fresh_type" to request.fresh_type,
            "ps" to request.ps,
            "fresh_idx" to request.fresh_idx,
            "feed_version" to request.feed_version,
            "homepage_ver" to request.homepage_ver,
            "web_location" to request.web_location,
            "seo_info" to request.seo_info
        )

        // Add optional parameters
        request.fresh_idx_1h?.let { params["fresh_idx_1h"] = it }
        request.brush?.let { params["brush"] = it }
        request.fetch_row?.let { params["fetch_row"] = it }
        request.y_num?.let { params["y_num"] = it }
        request.last_y_num?.let { params["last_y_num"] = it }
        request.screen?.let { params["screen"] = it }
        request.last_showlist?.let { params["last_showlist"] = it }
        request.uniq_id?.let { params["uniq_id"] = it }
        // w_rid and wts are generated by WBI sign, so we don't need to add them manually

        // Make API request with WBI signature using extension function
        return ApiClient.client.wbiGet(UrlConstants.ENDPOINT_HOME_RECOMMENDATION, params)
    }
}